### ISSUE TITLE
Webhook integration

### ISSUE THREAD

**Issue by tschnoelzer** [amuramoto/messenger-node#1]
Hi Alex,

thx for your work, exactly what I was looking for.

I have 1 integration questions, perhaps u can help:

How to use Webhook as a express server within google cloud functions?

Following this article express itself is easy to be wrapped:
https://codeburst.io/express-js-on-cloud-functions-for-firebase-86ed26f9144c

could not find a way for webhook.

best 

Timo

**Comment by amuramoto** [comment]
Hi @tschnoelzer! Sorry for the slow reply on this - I missed the email notification. I'm not very familiar with Google Cloud Functions, but based on the tutorial you linked, you should be able to call something like:

```
let app = Webhook.getInstance();
```

This returns the express.js `app` instance, which you can pass it to a cloud function handler.

Hope this helps! Glad you've found the SDK useful.
