### ISSUE TITLE
(#12) ids_for_apps requires version v2.9 or higher

### ISSUE THREAD

**Issue by meetpoladia** [amuramoto/messenger-node#4]
Getting this error while trying the ID Matching Client
{ error:
   { message: '(#12) ids_for_apps requires version v2.9 or higher',
     type: 'OAuthException',
     code: 12,
     fbtrace_id: 'EF+rXUGnOUy' } }

My Code -

const Messenger = require('messenger-node');
let conifg = {
  'page_token': 'xxxxx',
  'app_token': 'xxxxx', //optional
  'api_version': 'v2.11' //optional
}
const Client = new Messenger.Client(conifg);

Client.getMatchingAsids('xxxxx', 'PSID')
  .then(res => {
    console.log(res);
});

Thanks.

**Comment by amuramoto** [comment]
Can you remove the two `//optional` from your json object and retry?
