### ISSUE TITLE
Typescript typings?

### ISSUE THREAD

**Issue by tommedema** [amuramoto/messenger-node#6]
Are you interested in extending this with typescript typings? Or does Facebook have an official SDK for messenger APIs?

**Comment by amuramoto** [comment]
Sure, I happily accept pull requests if you want to contribute typings =) AFAIK FB doesn't have an official SDK, but there are some other OSS ones out there

**Comment by tommedema** [comment]
Thanks! On further review I decided to stick with a http client like `superagent`
